# Generated by Django 3.1.7 on 2021-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod_auth', '0005_auto_20210422_1311'),
        ('vod_auth', '0005_auto_20210422_1245'),
    ]

    operations = [
    ]
