# Generated by Django 3.1.6 on 2021-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
