# Generated by Django 3.1.7 on 2021-04-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the course', max_length=50)),
                ('short_description', models.CharField(help_text='One liner description for course', max_length=50)),
                ('description', models.CharField(help_text='Course description', max_length=1000)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor', to='vod.instructor')),
            ],
            options={
                'db_table': 'VOD_Course',
            },
        ),
    ]
