# Generated by Django 3.1.7 on 2021-04-13 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vod', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_courses', models.ManyToManyField(to='vod.Course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vod_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'VOD_Student',
            },
        ),
    ]
