# Generated by Django 3.1.7 on 2021-04-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the course module', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='vod.course')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the course', max_length=50)),
                ('description', models.CharField(help_text='Description of the video', max_length=250)),
                ('public_url', models.CharField(help_text='Stream URL of the demo video', max_length=300)),
                ('private_url', models.CharField(help_text='Stream URL of the full video', max_length=300)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='vod.coursemodule')),
            ],
        ),
    ]
