# Generated by Django 3.1.7 on 2021-04-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vod', '0004_coursemodule_modulevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='teacher',
        ),
        migrations.AddField(
            model_name='instructor',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vod.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vod.student')),
            ],
        ),
    ]
