# Generated by Django 3.1.7 on 2021-04-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0005_auto_20210413_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='', help_text='Course description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='', help_text='One liner description for course', max_length=50),
        ),
    ]
