# Generated by Django 3.1.7 on 2021-04-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0006_auto_20210413_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
    ]
