# Generated by Django 3.1.7 on 2021-04-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0013_delete_dummymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulevideo',
            old_name='course_highlight_order',
            new_name='video_highlight_order',
        ),
    ]
