# Generated by Django 3.1.7 on 2021-04-19 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0014_auto_20210418_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuxAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mux_assets', to='vod.modulevideo')),
            ],
        ),
    ]
