# Generated by Django 3.1.7 on 2021-04-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0015_muxasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='muxasset',
            name='playback_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.CreateModel(
            name='EnrollmentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=200, null=True)),
                ('razorpay_signature', models.CharField(max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vod.courseenrollment')),
            ],
        ),
    ]
