# Generated by Django 3.1.7 on 2021-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0016_auto_20210419_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
