# Generated by Django 3.1.7 on 2021-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0018_auto_20210420_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulevideo',
            name='dishabled',
            field=models.BooleanField(default=False),
        ),
    ]
